# -*- coding: utf-8 -*-
"""task_13_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5_Ntx-XeU5vExWEjRbMlLcY7k1nozzg
"""

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# загрузка данных
df = pd.read_csv('cafe_reviews.csv')

# загрузка модели
model_name = "blanchefort/rubert-base-cased-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# функция анализа тональности
def analyze_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    pred = torch.argmax(logits).item()

    # приведение к формату задания
    if pred == 0:
        return 0  # Neutral
    elif pred == 1:
        return 1  # Positive
    else:
        return 2  # Negative

# применение ко всем отзывам
df['predicted_sentiment'] = df['text'].astype(str).apply(analyze_sentiment)

# проверка
print(df.head())

import matplotlib.pyplot as plt

counts = df['predicted_sentiment'].value_counts().sort_index()

plt.figure(figsize=(6,4))
plt.bar(counts.index.astype(str), counts.values)

plt.xlabel("Тональность")
plt.ylabel("Количество отзывов")
plt.title("Распределение тональности отзывов (Predicted)")

plt.tight_layout()
plt.show()